### ISSUE TITLE
addSignedInput fails

### ISSUE THREAD

**Issue by achow101** [bitcoinj/bitcoinj#1081]
I am trying to write something using Bitcoinj and I am using the addSignedInput method to add and sign the inputs since I have found that sendRequests don't work for my purposes (specifying exactly what the inputs and outputs are as well as the fee). 

The transactions I am making are large transactions. They take 552 outputs from another transaction and combine those into one output. The problem I am having is that when I use addSignedInput looped to add all 552 inputs signed, I always get this error `mandatory-script-verify-flag-failed` from nodes when I broadcast. When I added in a loop to verify each input, I get an exception with message `Script resulted in a non-true stack: []`

Also, I use the same method in the transaction that produces those outputs. That transactions has 1 input, and the method works fine. 

Why does this happen? Can someone help me?

**Comment by mikehearn** [comment]
We should just remove addSignedInput. It's too hard to use correctly. The problem is you're signing the transaction and then changing it structurally afterwards.

You should just use a SendRequest. You can give a custom coin selector to pick the inputs you want, and add the outputs before using the completeTx() API to finish it off. You can also set the fee precisely.

Otherwise, add outputs and unsigned inputs, then sign each input individually using the lower level APIs.
