### ISSUE TITLE
Network issues in 0.14.4 on Android

### ISSUE THREAD

**Issue by btcontract** [bitcoinj/bitcoinj#1351]
I've spotted this behavior while running a `0.14.4` based wallet on a Xiaomi MI5 device (SDK version 25): after an app is running for some time, typically within 5-10 minutes, it stops receiving new blocks info without any indication of network issues (no related events fired).  

Peers clearly stay connected as an app does receive new incoming transactions but they don't get new confirmations (as well as the old ones).  

Restarting an app or changing network type on the fly (from WiFi to mobile for example) causes a reconnect and fixes an issue but in time it starts manifesting itself again.  

This does not happen in emulator and also stops happening on a device when `0.14.2` is used.

**Comment by schildbach** [comment]
Try putting your app (Bitcoin Wallet?) on the doze exceptions list. Does that help?

**Comment by btcontract** [comment]
Forgot to mention but doze was my first suspicion so I did make an explicit exception for an app and it did not solve an issue. I've also forced a phone to not go to sleep at all but it did not help either.  
The app is Simple Bitcoin Wallet, a wallet of mine.

**Comment by schildbach** [comment]
I guess I would start swapping more things. Try your app on another phone, try your app on mobile cellular data instead of WLAN (or vice versa), try Bitcoin Wallet on your phone, etc.

Since you already found there is a difference between bitcoinj 0.14.2 and 0.14.4, you could do a bisect to locate the problematic commit. I must admit that I doubt any change in 0.14.3 or 0.14.4 can cause this, as we didn't change anything concerned with the low level networking. I assume you looked at "adb logcat" and did not see any incoming block or transaction messages at all.

**Comment by btcontract** [comment]
Ok, I'll try all the options suggested. New incoming transaction messages always happen correctly, even after new block messages stop arriving.

**Comment by schildbach** [comment]
Also, try connecting exclusively to a node you control and have a look at it's debug.log.

**Comment by btcontract** [comment]
could not reproduce an issue
