### ISSUE TITLE
Implement sendheaders message (was: Segwit branch can't connect to peers)

### ISSUE THREAD

**Issue by btcontract** [bitcoinj/bitcoinj#1424]
Trying out the latest commit https://github.com/bitcoinj/bitcoinj/commit/5fa0262243b213e62a235b3a98dda5d7f2454707 and it drops peer connections, getting the following log output:

[https://pastebin.com/raw/xGgHWuZ1](https://pastebin.com/raw/xGgHWuZ1)

**Comment by schildbach** [comment]
In the segwit branch we incremented our own version to 70012, causing core to send us that `sendheaders` message. I think we should – on the master branch – step by step implement the changes necessary for incrementing the version 70001→70012.

For this case, I think should just implement the SendHeaders message including serialization and deserialization, but then ignore the message in PeerGroup because we don't advertize new blocks.

**Comment by globaltoken** [comment]
Same in #1429

**Comment by schildbach** [comment]
Fixed via #1425.
