### ISSUE TITLE
Copying Wallettemplate to separate file, issue with implemention project core in the build.gradle file

### ISSUE THREAD

**Issue by cryptobobbyx** [bitcoinj/bitcoinj#1633]
implementation project(':core')

When I try to import the copied wallet template file, I receive an error at the beginning that points to the implentation of project core in the build.gradle file of the wallet template. 

When I run the wallet template in a file that has the entire source code it runs perfectly. I am assuming there is an error in the dependancy that does not recognize what project core is. I am a beginner and appreciate any help. Thank you in advance :)!

**Comment by msgilligan** [comment]
You'll need to replace:

    implementation project(':core')

With:

    implementation "org.bitcoinj:bitcoinj-core:0.15.1"

Where `0.15.1` is the version of bitcoinj you are using. You'll also probably want to download the source from the tagged commit so that your source for `wallettemplate` is compatible with the released jar for `bitcoinj-core`.

This is because `project` in the Gradle context above means to reference a sibling subproject in a  multi-project Gradle build.

I hope this helps.

**Comment by msgilligan** [comment]
@schildbach This probably should have been asked on the mailing list, but I answered it above. I think we can close this issue now.

**Comment by schildbach** [comment]
Yes, thanks!
