### ISSUE TITLE
memory leak if remote peer doesn't reply to a ping

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [bitcoinj/bitcoinj#1719]
When we are sending pings to a Peer that never sends `Pong` back for any reason, the `org.bitcoinj.core.Peer#pendingPings` is getting filled with `PendingPing` instances that are never cleared. (Normally they are cleared only on Pong receival)

Can we throw old `PendingPings` away (add timeout)? Disconnect from such Peer (how)? 

Similar problem seems to be with `org.bitcoinj.core.Peer#pendingTxDownloads` that gets filled if some transactions never arrive(?).

**Comment by schildbach** [comment]
Yeah, there are probably some of such cases. In the case of ping/pong, if we don't do that already we could disconnect the peer after a timeout. I think disconnecting always destroys the instance and thus collects all the "lost" memory back.

**Comment by pvyhnal-generalbytes** [comment]
It seems that nothing is waiting for the Pong reply now. Can the peer remove itself from the PeerGroup when there is no pong or should the peergroup handle it? 

How about pendingTxDownloads, is it safe to do the same?

Thanks.

**Comment by schildbach** [comment]
I would rather not silently remove timed-out pings. I'd prefer disconnecting the offending peer. In any case, PR welcome.

**Comment by schildbach** [comment]
I just thought about this. I think rather than implementing a time-out I'd implement a limit of pending pings (per peer). So if e.g. 10 pings are pending, disconnect the peer and free up the used memory.

The reason is we use the ping/pong mechanism for protocol synchronization, basically to know when Bitcoin Core is finished replying with relevant data (the P2P protocol fails at this). This may lead to a quite delayed synchronzation pong.

**Comment by pvyhnal-generalbytes** [comment]
Resolved/merged in the linked PR
