### ISSUE TITLE
Can I lose my Wallet? - Wallet file writes ...

### ISSUE THREAD

**Issue by Tockra** [bitcoinj/bitcoinj#2020]
Hi Guys,

I'm a little bit confused by your documentation:
![image](https://user-images.githubusercontent.com/1353859/90160124-a5cea080-dd91-11ea-9108-a9fa339fd061.png)

Isn't the wallet a collection of keys which was computed by a initial generated key?
So when does the wallet changes? Your documentation says after a transaction the wallet changed and needed to written again into a file:
![image](https://user-images.githubusercontent.com/1353859/90161129-fbf01380-dd92-11ea-93a2-738b03e3b571.png)

I don't understand why.
Can I lose my crypto currency when I saving the seed of my wallet?:
![image](https://user-images.githubusercontent.com/1353859/90160382-ff36cf80-dd91-11ea-8f24-ede2310ce578.png)

So after I created that wallet and used it a while (send coins, received coins with fresh addresses: https://bitcoinj.github.io/javadoc/0.15.7/org/bitcoinj/wallet/Wallet.html#freshReceiveAddress--), the wallet file changed over the time.
But when I lose that wallet file and I will use my saved seed with the birthtime, will I get all coins back, which was sent to that wallet over the time?
I would say yes, but you confused me with your documentation.

Thank you for your answeres ;)

T

**Comment by schildbach** [comment]
You as a wallet developer are free to decide on using deterministic wallets (keys derived from a common seed) or not. Bitcoinj also allows to import arbitrary keys into your wallet.

If your wallet is deterministic and the seed is backed up, then at least your users won't loose any funds if they manage to restore from the seed.

**However:**

Bitcoinj wallets contain more than just keys. If you loose the transaction history, you must go through a potentially lengthy and traffic intensive blockchain sync process again. Transactions can have metadata like memos which are lost because the blockchain doesn't store any user metadata. So (auto-)saving is still somewhat important even for deterministic wallets.

**Comment by Tockra** [comment]
Why is that a good idea to store two different things, which are independent  in one file (history and keys) ?
Is this common?

**Comment by schildbach** [comment]
Well, I guess the reason is files can be written atomically. Two (or more) files would need to be sychronized at filesystem level, and we have only little control on that level in Java.

Mike Hearn (the former maintainer of this project) once described the idea of using a database for storing the wallet. So far, no one bothered to implement that idea.
