### ISSUE TITLE
Reading wallet.dat

### ISSUE THREAD

**Issue by OlMi1** [bitcoinj/bitcoinj#2442]
I know this is not a help forum, but I can't figure out wether it's possible to read a wallet.dat generated by Bitcoin Core with this libarary and if yes, how. Thank you!

**Comment by msgilligan** [comment]
No, you can't. And yes, you shouldn't be asking here.

`wallet.db` is in BerkeleyDB format: https://en.wikipedia.org/wiki/Berkeley_DB

There are (or at least used to be) Java bindings for BerkeleyDB so if you must use Java, I'd look for that. Otherwise I'd see if any of the `bitcoin-cli` commands does what your want, or look for a utility called "PyWallet".  Good luck. 

@schildbach Please close this issue.
