### ISSUE TITLE
How can I create a taproot address from my key?

### ISSUE THREAD

**Issue by mehranj73** [bitcoinj/bitcoinj#2560]
How can I create a taproot address from my key?
```
    val key = ECKey.fromPrivate(BigInteger("1000"))
    val a = SegwitAddress.fromKey(params, key, ScriptType.P2TR).toString()
    println(a)
```

**Comment by msgilligan** [comment]
I don't think **bitcoinj** currently supports creating a taproot address from a key. As of v0.16 it supports sending to taproot addresses, but probably those need to be created from strings. Is this correct @schildbach ?

Full Taproot support is planned, but not available yet: See Issue #1949.

**Comment by schildbach** [comment]
Yes, I think that's correct.

I'll close this question. @mehranj73 if you've got further question, please consider joining our [Matrix space](https://bitcoinj.org/#community).

**Comment by ronaldoguedess** [comment]
Any news about Taprrot P2TR address?

**Comment by msgilligan** [comment]
We are making progress on multiple fronts. No releases yet, though. Search some of the other issues and PRs and look at the `secp256k1-jdk` project.

**Comment by ronaldoguedess** [comment]
I found a working solution using two libraries (BitcoinJ + WalletCore) to generate Taproot addresses for both mainnet and testnet.

**The Problem:**
WalletCore generates Taproot addresses perfectly, but only for mainnet. Since my app needs to support both networks, I needed an alternative approach.
The Solution:

Generate the Taproot address on mainnet using WalletCore (always reliable and correct)
Extract the witness program (tweaked pubkey - 32 bytes) from that mainnet address
Reuse the witness program to create the testnet address with HRP "tb" using Bech32m encoding

This way, I leverage WalletCore's correct tweak calculation (BIP 341) and simply change the network prefix when needed.
Features:
✅ Supports generation via Seed Phrase
✅ Supports generation via Private Key directly
✅ Mainnet (bc1p...) and Testnet (tb1p...)
✅ 100% functional and tested

If anyone needs it, I can share the complete Bech32m helper functions code!

I will use this soluction until BitcoinJ release the final version. Thanks for your reply @msgilligan .

**Comment by msgilligan** [comment]
> If anyone needs it, I can share the complete Bech32m helper functions code!

Yes, please share!
