### ISSUE TITLE
GitHub Actions: macos-12 image is about to be removed

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#3536]
According to https://github.com/actions/runner-images, the `macos-12` runner image is deprecated and according to an email I received from GitHub, it will go away on December 3rd, 2024. This will fail our GitHub actions and thus our builds.

Apparently we can't simply update to `macos-13/14/15`, because those switch the architecture to Arm64 and JDK 8 is not available for it. We currently need JDK 8 to test against as a "surrogate" for the Android API. Ideally we'd test against the real Android API but that's not easy to do.

**Comment by msgilligan** [comment]
We *can* simply upgrade to macOS-13, because it is still an x86-64 architecture.

Related PRs:

* https://github.com/bitcoinj/bitcoinj/pull/3454 Removes "oldest JDK" test entirely
* https://github.com/bitcoinj/bitcoinj/pull/3455 Child of 3454, that upgrades to macOS-14
* https://github.com/bitcoinj/bitcoinj/pull/3456 Upgrades "oldest JDK" test from JDK 8 to JDK 11
* https://github.com/bitcoinj/bitcoinj/pull/3457 Child of 3456, that upgrades to macOS-14

But since we want to keep the Jdk8 tests we will need to disable them for macOS-14/15 with either conditional logic in the Gradle or in the GitHub workflow (by making the ` -PtestJdk8=true` argument to Gradle conditional)

**Comment by schildbach** [comment]
> We _can_ simply upgrade to macOS-13, because it is still an x86-64 architecture.

Ah sorry, didn't realize that. I'm trying it now: https://github.com/bitcoinj/bitcoinj/pull/3537

**Comment by msgilligan** [comment]
> > We _can_ simply upgrade to macOS-13, because it is still an x86-64 architecture.
> 
> Ah sorry, didn't realize that. I'm trying it now: #3537

Yeah, we should just merge 3537 and worry about macOS-14 and making the JDK 8 tests conditional at a later time.

**Comment by schildbach** [comment]
Fixed via #3537 on master, 0.17, 0.16.
