### ISSUE TITLE
Migrate Coin, Fiat, Monetary classes to Java Money

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#980]
Originally reported on Google Code with ID 614

```
Now that the Java Money (JSR 354) API Backport is available and should support Android
/ Java 6, it should be possible to modify the bitcoinj Monetary classes to be more
compatible with this implementation.

As a rough proposal, I suggest the following:

1) `Coin` should extend the `NumberValue` class
2) `Fiat` should implement `MonetaryAmount` (or perhaps be deprecated in favor of MonetaryAmount)
3) A MonetaryAmount subclass should be created for a Bitcoin (value, currency) pair

I realize this is not going to be a popular request so soon after the conversion to
`Coin` and while JavaMoney is so new. But I wanted to create the issue for discussion
and to raise awareness so this change might be included in a future release.

The Specification supports many important and interesting use cases (such as crypto
currency and currency exchanges) and even includes a link to bitcoinj in the appendix.

References
---------

The JavaMoney project home page:
http://javamoney.github.io

The JavaMoney specification:
https://github.com/JavaMoney/jsr354-api/blob/master/src/main/asciidoc/JavaMoneySpecification.adoc

The JavaMoney API (Java 8+)
https://github.com/JavaMoney/jsr354-api

The JavaMoney Reference Implementation (Java 8+):
https://github.com/JavaMoney/jsr354-ri

The Java Money API Backport (Java 6/7):
https://github.com/JavaMoney/jsr354-api-bp

The JavaMoney Reference Implementation Backport (Java 7):
https://github.com/JavaMoney/jsr354-ri-bp


```

Reported by `sean@msgilligan.com` on 2015-04-10 01:17:46

**Comment by msgilligan** [comment]
Nice to see this over on GitHub :) Thanks, @mikehearn !

**Comment by stokito** [comment]
JFYI In JavaMoney examples [there is small bitcoin currency provider](https://github.com/JavaMoney/javamoney-shelter/tree/master/digital-currency/bitcoin)

And some [presentation](http://www.slideshare.net/keilw/bitcoin-payment-instrument-or-object-of-speculation-smwhh-2014) from one of the authors of JavaMoney

When you start to implement this issue please leave a comment here or me know. I'm working on migration money classes in my company to JavaMoney and hope that some of my experience may be useful for you.

Thank

**Comment by msgilligan** [comment]
@stokito I've created a module in my `bitcoinj-addons` repository that a Bitcoin currency provider based on the one from `javamoney-shelter`. I've also added a prototype adapter that will wrap and adapt the `Exchange` interface from the extensive [XChange](http://knowm.org/open-source/xchange/) library of Bitcoin exchange clients. See the [README section](https://github.com/msgilligan/bitcoinj-addons#bitcoinj-money)

**Comment by msgilligan** [comment]
An update on this:

1. The JavaMoney work that I have done is in the https://github.com/ConsensusJ/consensusj project in the `consensusj-currency` and `consensusj-exchange` modules. Feel free to try it out and submit issues or pull-requests.
2. JavaMoney will not be bundled with the JDK as some had originally hoped.
3. Although I am the one who originally opened this issue, I now believe -- partly because of (2) -- that it would be better _not_ to make `bitcoinj-core` dependent upon JavaMoney.
4. I do think that JavaMoney is a useful library for some applications and (via the ConsensusJ modules) can be useful in Bitcoin applications.

@schildbach I opened this issue on Google Code, but since Mike imported it to GitHub, I can't close it. I recommend we close it.
